### ISSUE TITLE
Do you have mnn demo code?

### ISSUE THREAD

**Issue by CYL-Roy** [dog-qiuqiu/Yolo-FastestV2#48]
Do you have mnn demo code?
我的onnx跟mnn結果不一樣...

**Comment by CYL-Roy** [comment]
ncnn跟onnx結果可以一致
但mnn就output連array維度數量都不一樣

**Comment by CYL-Roy** [comment]
https://blog.csdn.net/weixin_39266208/article/details/122131303

**Comment by qing-shang** [comment]
> https://blog.csdn.net/weixin_39266208/article/details/122131303

onnxruntime c++有例子吗
